import { createClient } from "@supabase/supabase-js";
import * as SecureStore from "expo-secure-store";
import "react-native-url-polyfill/auto";

// 💡 NOTE: You should replace './database.types' with the path to the
// file generated by the Supabase CLI: `supabase gen types typescript --project-id <YOUR_PROJECT_ID> > database.types.ts`
// import { Database } from './database.types';

// --- Configuration ---
// These should be loaded from your .env file or Expo config
const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!;

// --- SecureStore Chunking Adapter (Fixes the 2048 Byte Limit) ---

const MAX_CHUNK_SIZE = 2000;

const chunkString = (str: string, size: number): string[] => {
  const numChunks = Math.ceil(str.length / size);
  return Array.from({ length: numChunks }, (_, i) =>
    str.substring(i * size, i * size + size)
  );
};

const ExpoSecureStoreAdapter = {
  // --- Get Item (READ) ---
  getItem: async (key: string): Promise<string | null> => {
    // 1. Check for the single, non-chunked value first
    const simpleValue = await SecureStore.getItemAsync(key);
    if (simpleValue !== null) {
      return simpleValue;
    }

    // 2. If no simple value, try to reconstruct from chunks
    let chunkedValue = "";
    let index = 0;
    let foundChunk = false;

    while (true) {
      const v = await SecureStore.getItemAsync(`${key}_chunk_${index}`);
      if (v === null) {
        break;
      }
      chunkedValue += v;
      foundChunk = true;
      index++;
    }
    return foundChunk ? chunkedValue : null;
  },

  // --- Set Item (WRITE) ---
  setItem: async (key: string, value: string) => {
    // Always clean up existing data first
    await ExpoSecureStoreAdapter.removeItem(key);

    if (value.length <= MAX_CHUNK_SIZE) {
      // Store as a single, simple key
      await SecureStore.setItemAsync(key, value);
    } else {
      // Store as chunks
      const values = chunkString(value, MAX_CHUNK_SIZE);
      await Promise.all(
        values.map((v, i) => SecureStore.setItemAsync(`${key}_chunk_${i}`, v))
      );
    }
  },

  // --- Remove Item (DELETE) ---
  removeItem: async (key: string) => {
    // 1. Delete the simple, non-chunked key
    await SecureStore.deleteItemAsync(key);

    // 2. Loop and delete chunks
    let index = 0;
    while (true) {
      const chunkKey = `${key}_chunk_${index}`;
      const chunkExists = await SecureStore.getItemAsync(chunkKey);

      if (chunkExists !== null) {
        await SecureStore.deleteItemAsync(chunkKey);
      } else {
        break;
      }
      index++;
    }
  },
};

// --- Supabase Client Initialization ---
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    // 🔑 Use the custom chunking adapter for secure, large storage
    storage: ExpoSecureStoreAdapter,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
  // db: {
  //   // Optional: Set default schema if not 'public'
  //   schema: 'public',
  // }
});
// If you generate types, uncomment this line:
// export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, { /* ... auth config ... */ });
